"""Add unit_quiz_placements table

Revision ID: 01346773eff8
Revises: 3e823b45369d
Create Date: 2025-10-08 13:52:52.853621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01346773eff8'
down_revision = '3e823b45369d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_quiz_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('unit_key', sa.String(length=128), nullable=False),
    sa.Column('course_key', sa.String(length=128), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=False),
    sa.Column('student_number', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_quiz_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unit_quiz_attempt_submitted_at'), ['submitted_at'], unique=False)

    op.create_table('unit_quiz_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unit_quiz_placements', schema=None) as batch_op:
        batch_op.create_index('idx_course_chapter_position', ['course_id', 'chapter_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_quiz_placements_chapter_id'), ['chapter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_quiz_placements_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_unit_quiz_placements_question_id'), ['question_id'], unique=False)
        batch_op.create_index('uq_course_chapter_question', ['course_id', 'chapter_id', 'question_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unit_quiz_placements', schema=None) as batch_op:
        batch_op.drop_index('uq_course_chapter_question')
        batch_op.drop_index(batch_op.f('ix_unit_quiz_placements_question_id'))
        batch_op.drop_index(batch_op.f('ix_unit_quiz_placements_course_id'))
        batch_op.drop_index(batch_op.f('ix_unit_quiz_placements_chapter_id'))
        batch_op.drop_index('idx_course_chapter_position')

    op.drop_table('unit_quiz_placements')
    with op.batch_alter_table('unit_quiz_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unit_quiz_attempt_submitted_at'))

    op.drop_table('unit_quiz_attempt')
    # ### end Alembic commands ###
