"""Add bookings table

Revision ID: 0c52a8b41113
Revises: 7464d94bb281
Create Date: 2025-05-28 14:39:18.761358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c52a8b41113'
down_revision = '7464d94bb281'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('course_title', sa.String(length=200), nullable=True),
    sa.Column('student_name', sa.String(length=100), nullable=True),
    sa.Column('student_email', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orphaned_final_submissions')
    with op.batch_alter_table('final_assessment_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_assessment_submission', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('orphaned_final_submissions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('video_filename', sa.TEXT(), nullable=True),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('percentage', sa.REAL(), nullable=True),
    sa.Column('review_status', sa.TEXT(), nullable=True),
    sa.Column('submitted_at', sa.NUMERIC(), nullable=True)
    )
    op.drop_table('booking')
    # ### end Alembic commands ###
