"""add payments table

Revision ID: 10b971a57a23
Revises: be318605e632
Create Date: 2025-09-02 14:56:18.401268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10b971a57a23'
down_revision = 'be318605e632'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('m_payment_id', sa.String(length=64), nullable=True),
    sa.Column('pf_payment_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('buyer_name', sa.String(length=120), nullable=True),
    sa.Column('buyer_email', sa.String(length=120), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.String(length=8), nullable=True),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_buyer_email'), ['buyer_email'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_m_payment_id'), ['m_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_pf_payment_id'), ['pf_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_student_id'))
        batch_op.drop_index(batch_op.f('ix_payments_pf_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_m_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_course_id'))
        batch_op.drop_index(batch_op.f('ix_payments_buyer_email'))

    op.drop_table('payments')
    # ### end Alembic commands ###
