"""Add ModerationEscalationLog table

Revision ID: 114904d6bf30
Revises: ac36e705288e
Create Date: 2025-05-29 10:40:34.074897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114904d6bf30'
down_revision = 'ac36e705288e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_escalation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('moderation_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('escalated_by', sa.String(length=100), nullable=False),
    sa.Column('escalation_date', sa.DateTime(), nullable=True),
    sa.Column('action_taken', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['moderation_id'], ['moderation_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation_escalation_log')
    # ### end Alembic commands ###
