"""Add answers_json and questions_json to FinalAssessmentSubmission

Revision ID: 22176b8e927d
Revises: a45e33319dea
Create Date: 2025-10-02 11:21:42.432178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22176b8e927d'
down_revision = 'a45e33319dea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_assessment_submission', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_key', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('answers_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('questions_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_assessment_submission', schema=None) as batch_op:
        batch_op.drop_column('questions_json')
        batch_op.drop_column('answers_json')
        batch_op.drop_column('final_key')

    # ### end Alembic commands ###
