"""Make studentattemptid nullable

Revision ID: 3728a46da2b3
Revises: 114904d6bf30
Create Date: 2025-06-02 12:17:10.603832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3728a46da2b3'
down_revision = '114904d6bf30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_form', schema=None) as batch_op:
        batch_op.alter_column('studentattemptid',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_form', schema=None) as batch_op:
        batch_op.alter_column('studentattemptid',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
