"""Added otp field to Student

Revision ID: 3c200471a5aa
Revises: 51ea4b0f24d6
Create Date: 2025-02-18 07:58:19.302703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c200471a5aa'
down_revision = '51ea4b0f24d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp', sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('otp')

    # ### end Alembic commands ###
