"""Add course_time to bookings

Revision ID: 46825ac5e6de
Revises: 5c31bffac5c0
Create Date: 2025-05-28 14:47:49.749745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46825ac5e6de'
down_revision = '5c31bffac5c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_time', sa.String(length=50), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Date(),
               existing_nullable=True)
        batch_op.alter_column('student_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=120),
               existing_nullable=True)
        batch_op.drop_column('time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.VARCHAR(length=50), nullable=True))
        batch_op.alter_column('student_name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('course_time')

    # ### end Alembic commands ###
