"""Create final_assessment_attempts table

Revision ID: 4dbbdb513559
Revises: c99752274a6b
Create Date: 2025-10-02 12:09:04.949497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dbbdb513559'
down_revision = 'c99752274a6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airside_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('student_number', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpas_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('student_number', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_assessment_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_number', sa.String(length=64), nullable=False),
    sa.Column('course_key', sa.String(length=64), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_assessment_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_final_assessment_attempts_course_key'), ['course_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_final_assessment_attempts_student_number'), ['student_number'], unique=False)

    op.create_table('proctor_violations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('student_number', sa.String(length=64), nullable=True),
    sa.Column('course_key', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('extra_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctor_violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proctor_violations_course_key'), ['course_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_proctor_violations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_proctor_violations_student_number'), ['student_number'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proctor_violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proctor_violations_student_number'))
        batch_op.drop_index(batch_op.f('ix_proctor_violations_created_at'))
        batch_op.drop_index(batch_op.f('ix_proctor_violations_course_key'))

    op.drop_table('proctor_violations')
    with op.batch_alter_table('final_assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_final_assessment_attempts_student_number'))
        batch_op.drop_index(batch_op.f('ix_final_assessment_attempts_course_key'))

    op.drop_table('final_assessment_attempts')
    op.drop_table('rpas_attempt')
    op.drop_table('airside_attempt')
    # ### end Alembic commands ###
