"""Added name and surname fields

Revision ID: 51ea4b0f24d6
Revises: cb7fea5e2d5e
Create Date: 2025-02-18 07:54:28.814826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ea4b0f24d6'
down_revision = 'cb7fea5e2d5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=50), nullable=False))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
