"""Fix support ticket model

Revision ID: 56c6f54fd90e
Revises: 72a37ed32f06
Create Date: 2025-02-18 16:26:35.233334

"""
from alembic import op
import sqlalchemy as sa


# Revision identifiers, used by Alembic.
revision = '56c6f54fd90e'
down_revision = '72a37ed32f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('problem_description', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

        batch_op.alter_column('email',
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=120),
            existing_nullable=False)

        # ✅ Explicitly name the foreign key constraint
        batch_op.create_foreign_key("fk_support_ticket_course", 'course', ['course_id'], ['id'])

        # ✅ Ensure the columns exist before dropping
        inspector = sa.inspect(op.get_bind())
        columns = [col["name"] for col in inspector.get_columns("support_ticket")]

        if "student_name" in columns:
            batch_op.drop_column("student_name")

        if "description" in columns:
            batch_op.drop_column("description")

        if "course_title" in columns:
            batch_op.drop_column("course_title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_title', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('student_name', sa.VARCHAR(length=100), nullable=False))

        batch_op.drop_constraint("fk_support_ticket_course", type_="foreignkey")

        batch_op.alter_column('email',
            existing_type=sa.String(length=120),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False)

        batch_op.drop_column('created_at')
        batch_op.drop_column('problem_description')
        batch_op.drop_column('course_id')
    # ### end Alembic commands ###