"""add course_feedback table

Revision ID: 5aba8d9216bd
Revises: 5de1dc198721
Create Date: 2025-10-13 08:57:37.336608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5aba8d9216bd'
down_revision = '5de1dc198721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=True),
    sa.Column('q_navigate', sa.Integer(), nullable=False),
    sa.Column('q_understand', sa.Integer(), nullable=False),
    sa.Column('q_apply', sa.Integer(), nullable=False),
    sa.Column('q_value', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('confirm_own', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_feedback_student_course')
    )
    op.create_table('quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('qtype', sa.String(length=20), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_chapter_id'), ['chapter_id'], unique=False)

    op.create_table('quiz_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_option', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_option_question_id'), ['question_id'], unique=False)

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_questions_chapter_id')

    op.drop_table('quiz_questions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('options_json', sa.TEXT(), nullable=False),
    sa.Column('correct_index', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index('ix_quiz_questions_chapter_id', ['chapter_id'], unique=False)

    with op.batch_alter_table('quiz_option', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_option_question_id'))

    op.drop_table('quiz_option')
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_chapter_id'))

    op.drop_table('quiz_question')
    op.drop_table('course_feedback')
    # ### end Alembic commands ###
