"""Add course time to bookings

Revision ID: 5c31bffac5c0
Revises: 0c52a8b41113
Create Date: 2025-05-28 14:43:55.490529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c31bffac5c0'
down_revision = '0c52a8b41113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('time')

    # ### end Alembic commands ###
