"""add quiz model and chapter_type

Revision ID: 5de1dc198721
Revises: 899bc5d65aa6
Create Date: 2025-10-10 10:09:24.198138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de1dc198721'
down_revision = '899bc5d65aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_quiz_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(length=10), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('correct', sa.String(length=10), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter_quiz_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chapter_quiz_question_chapter_id'), ['chapter_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_quiz_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chapter_quiz_question_chapter_id'))

    op.drop_table('chapter_quiz_question')
    # ### end Alembic commands ###
