"""Company portal tables

Revision ID: 65c0e157d0ac
Revises: b8c401e54c50
Create Date: 2025-10-24 10:43:40.078287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c0e157d0ac'
down_revision = 'b8c401e54c50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('reg_no', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=240), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=160), nullable=True),
    sa.Column('contact_phone', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('national_id', sa.String(length=40), nullable=True),
    sa.Column('passport_no', sa.String(length=40), nullable=True),
    sa.Column('position', sa.String(length=120), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_employee', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_employee_email'), ['email'], unique=False)

    op.create_table('company_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('company_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_company_user_email'), ['email'], unique=True)

    op.create_table('employee_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=260), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['company_employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_document')
    with op.batch_alter_table('company_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_user_email'))

    op.drop_table('company_user')
    with op.batch_alter_table('company_employee', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_company_employee_email'))

    op.drop_table('company_employee')
    op.drop_table('company')
    # ### end Alembic commands ###
