"""Add quiz_data to CourseChapter

Revision ID: 69bc35fcae00
Revises: 985953ba174c
Create Date: 2025-04-07 15:16:45.361307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69bc35fcae00'
down_revision = '985953ba174c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.drop_column('quiz_data')

    # ### end Alembic commands ###
