"""Add chapter_type to CourseChapter

Revision ID: 7e1c6b1f430a
Revises: f7f13690eabe
Create Date: 2025-03-31 12:33:25.910110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e1c6b1f430a'
down_revision = 'f7f13690eabe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('chapter_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.drop_column('chapter_type')

    # ### end Alembic commands ###
