"""add quiz_questions table

Revision ID: 899bc5d65aa6
Revises: 01346773eff8
Create Date: 2025-10-10 09:33:01.362015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '899bc5d65aa6'
down_revision = '01346773eff8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_chapter_id'), ['chapter_id'], unique=False)

    with op.batch_alter_table('course_chapters', schema=None) as batch_op:
        batch_op.drop_index('ix_course_chapters_slug')

    op.drop_table('course_chapters')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_chapters',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('slug', sa.VARCHAR(length=128), nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('chapter_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quiz_data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['course_chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_chapters', schema=None) as batch_op:
        batch_op.create_index('ix_course_chapters_slug', ['slug'], unique=False)

    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_chapter_id'))

    op.drop_table('quiz_questions')
    # ### end Alembic commands ###
