"""Add ModerationForm model

Revision ID: 985953ba174c
Revises: 4175f5ad5cda
Create Date: 2025-04-04 11:44:07.235292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '985953ba174c'
down_revision = '4175f5ad5cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moderation_form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studentattemptid', sa.Integer(), nullable=False),
    sa.Column('studentname', sa.String(length=100), nullable=False),
    sa.Column('studentid', sa.String(length=100), nullable=False),
    sa.Column('coursename', sa.String(length=100), nullable=False),
    sa.Column('courseid', sa.String(length=100), nullable=False),
    sa.Column('moderatorname', sa.String(length=100), nullable=False),
    sa.Column('coursecompletiondate', sa.String(length=100), nullable=False),
    sa.Column('moderationdate', sa.String(length=100), nullable=False),
    sa.Column('question1', sa.String(length=10), nullable=False),
    sa.Column('question2', sa.String(length=10), nullable=False),
    sa.Column('question3', sa.String(length=10), nullable=False),
    sa.Column('question4', sa.String(length=10), nullable=False),
    sa.Column('question5', sa.String(length=10), nullable=False),
    sa.Column('question6', sa.String(length=10), nullable=False),
    sa.Column('question7', sa.String(length=10), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentattemptid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moderation_form')
    # ### end Alembic commands ###
