"""add appeal review audit fields

Revision ID: 9b7d3e1f5a2c
Revises: 8f1c2a9d4b6e
Create Date: 2026-09-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b7d3e1f5a2c'
down_revision = '8f1c2a9d4b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeal_dispute', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('reviewed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appeal_dispute', schema=None) as batch_op:
        batch_op.drop_column('reviewed_at')
        batch_op.drop_column('reviewed_by')
    # ### end Alembic commands ###
