"""create airside_attempt

Revision ID: a330c8e4a557
Revises: d3dc55b32fd6
Create Date: 2025-08-17 14:15:39.009968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a330c8e4a557'
down_revision = 'd3dc55b32fd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airside_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('answers_json', sa.Text(), nullable=True),
    sa.Column('video_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_assessment_question', schema=None) as batch_op:
        batch_op.drop_index('idx_faq_course_code')
        batch_op.create_index(batch_op.f('ix_final_assessment_question_course_code'), ['course_code'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_assessment_question', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_final_assessment_question_course_code'))
        batch_op.create_index('idx_faq_course_code', ['course_code'], unique=False)

    op.drop_table('airside_attempt')
    # ### end Alembic commands ###
