"""add popia_consent table

Revision ID: a45e33319dea
Revises: ca56660d9121
Create Date: 2025-09-30 09:39:44.943437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45e33319dea'
down_revision = 'ca56660d9121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popia_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'version', name='uq_popia_student_version')
    )
    with op.batch_alter_table('popia_consent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_popia_consent_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_popia_consent_version'), ['version'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('popia_consent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_popia_consent_version'))
        batch_op.drop_index(batch_op.f('ix_popia_consent_student_id'))

    op.drop_table('popia_consent')
    # ### end Alembic commands ###
