"""Add video_filename and admin_note to ModerationForm

Revision ID: ac36e705288e
Revises: 46825ac5e6de
Create Date: 2025-05-29 10:39:22.733884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac36e705288e'
down_revision = '46825ac5e6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_filename', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('admin_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moderation_form', schema=None) as batch_op:
        batch_op.drop_column('admin_note')
        batch_op.drop_column('video_filename')

    # ### end Alembic commands ###
