"""Add FinalAssessmentAttempt model (SQLite-safe)

Revision ID: b31a0cc7d40b
Revises: c7ea090a610a
Create Date: 2025-08-13

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b31a0cc7d40b'
down_revision = 'c7ea090a610a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Create the attempts table (only the new stuff we actually need)
    op.create_table(
        'final_assessment_attempts',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('student_id', sa.Integer(), nullable=True),
        sa.Column('student_number', sa.String(length=64), nullable=False),
        sa.Column('course_key', sa.String(length=64), nullable=False),
        sa.Column('course_id', sa.Integer(), nullable=True),

        sa.Column('attempt_no', sa.Integer(), nullable=False, server_default='1'),
        sa.Column('submitted_at', sa.DateTime(), nullable=True),

        sa.Column('total_questions', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('correct_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('percentage', sa.Float(), nullable=False, server_default='0'),

        sa.Column('passed', sa.Boolean(), nullable=False, server_default=sa.text('0')),

        sa.Column('video_filename', sa.String(length=512), nullable=True),
        sa.Column('answers_json', sa.Text(), nullable=True),

        sa.Column('review_status', sa.String(length=32), nullable=False, server_default='pending'),
    )

    op.create_index(
        'ix_final_assessment_attempts_student_number',
        'final_assessment_attempts',
        ['student_number']
    )
    op.create_index(
        'ix_final_assessment_attempts_course_key',
        'final_assessment_attempts',
        ['course_key']
    )

    # NOTE:
    # We intentionally DO NOT touch final_assessment_question here.
    # The autogenerated migration tried to drop an unnamed FK/index,
    # which fails on SQLite. Skipping keeps this migration SQLite-safe.


def downgrade() -> None:
    # Drop indexes then table
    op.drop_index('ix_final_assessment_attempts_course_key', table_name='final_assessment_attempts')
    op.drop_index('ix_final_assessment_attempts_student_number', table_name='final_assessment_attempts')
    op.drop_table('final_assessment_attempts')