"""Add reset_count column

Revision ID: baa80b7c2e96
Revises: 3fe665f8891e
Create Date: 2025-03-03 13:00:14.832541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa80b7c2e96'
down_revision = '3fe665f8891e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chapter_progress')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('selfie',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('id_upload',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('otp_code')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('otp_code', sa.VARCHAR(length=6), nullable=True))
        batch_op.alter_column('id_upload',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('selfie',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    op.create_table('chapter_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('acknowledged', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
