"""add payments table

Revision ID: be318605e632
Revises: 637ba139b7b5
Create Date: 2025-08-22 14:16:48.010729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be318605e632'
down_revision = '637ba139b7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('final_assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_final_assessment_attempts_course_key')
        batch_op.drop_index('ix_final_assessment_attempts_student_number')

    op.drop_table('final_assessment_attempts')
    op.drop_table('chapter_progress')
    op.drop_table('rpas_attempt')
    op.drop_table('course_chapter')
    op.drop_table('quiz')
    op.drop_table('course_enrollment')
    op.drop_table('final_assessment_quiz')
    op.drop_table('course')
    op.drop_table('module')
    op.drop_table('airside_attempt')
    op.drop_table('_alembic_tmp_airside_attempt')
    op.drop_table('user')
    op.drop_table('moderation_form')
    op.drop_table('support_ticket')
    with op.batch_alter_table('proctor_violations', schema=None) as batch_op:
        batch_op.drop_index('ix_proctor_violations_course_key')
        batch_op.drop_index('ix_proctor_violations_created_at')
        batch_op.drop_index('ix_proctor_violations_student_number')

    op.drop_table('proctor_violations')
    op.drop_table('student_final_result')
    op.drop_table('announcement')
    op.drop_table('violation_log')
    op.drop_table('course_progress')
    op.drop_table('moderation_escalation_log')
    op.drop_table('final_assessment_submission')
    op.drop_table('booking')
    op.drop_table('student')
    with op.batch_alter_table('assessment_config', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_config_course_code')

    op.drop_table('assessment_config')
    with op.batch_alter_table('final_assessment_question', schema=None) as batch_op:
        batch_op.drop_index('idx_faq_course_code')

    op.drop_table('final_assessment_question')
    op.drop_table('certificate_log')
    op.drop_table('sub_chapter')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_chapter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificate_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('issued_at', sa.DATETIME(), nullable=True),
    sa.Column('reissued', sa.BOOLEAN(), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_assessment_question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option_b', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option_c', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option_d', sa.VARCHAR(length=255), nullable=False),
    sa.Column('correct_option', sa.VARCHAR(length=1), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_assessment_question', schema=None) as batch_op:
        batch_op.create_index('idx_faq_course_code', ['course_code'], unique=False)

    op.create_table('assessment_config',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_code', sa.VARCHAR(length=64), nullable=False),
    sa.Column('title', sa.VARCHAR(length=160), nullable=False),
    sa.Column('pass_mark', sa.INTEGER(), nullable=False),
    sa.Column('time_limit_minutes', sa.INTEGER(), nullable=False),
    sa.Column('attempts_allowed', sa.INTEGER(), nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('question_source_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('limit_questions', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_config', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_config_course_code', ['course_code'], unique=1)

    op.create_table('student',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=8), nullable=False),
    sa.Column('national_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=15), nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('selfie_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_banned', sa.BOOLEAN(), nullable=True),
    sa.Column('registration_date', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=50), nullable=False),
    sa.Column('otp', sa.VARCHAR(length=8), nullable=True),
    sa.Column('is_suspended', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('national_id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_time', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('course_title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('student_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('student_email', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_assessment_submission',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=True),
    sa.Column('total_questions', sa.INTEGER(), nullable=True),
    sa.Column('percentage', sa.FLOAT(), nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=50), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('submitted_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('moderation_escalation_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('moderation_id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('course_id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('escalated_by', sa.VARCHAR(length=100), nullable=False),
    sa.Column('escalation_date', sa.DATETIME(), nullable=True),
    sa.Column('action_taken', sa.VARCHAR(length=20), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.Column('reviewed_by', sa.VARCHAR(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['moderation_id'], ['moderation_form.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('chapter_id', sa.INTEGER(), nullable=False),
    sa.Column('completed', sa.BOOLEAN(), nullable=True),
    sa.Column('reset_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['course_chapter.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=8), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_final_result',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.INTEGER(), nullable=False),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_violations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('course_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('extra_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctor_violations', schema=None) as batch_op:
        batch_op.create_index('ix_proctor_violations_student_number', ['student_number'], unique=False)
        batch_op.create_index('ix_proctor_violations_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_proctor_violations_course_key', ['course_key'], unique=False)

    op.create_table('support_ticket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ticket_id', sa.VARCHAR(length=10), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('problem_description', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='fk_support_ticket_course'),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_id')
    )
    op.create_table('moderation_form',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studentattemptid', sa.INTEGER(), nullable=True),
    sa.Column('studentname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('studentid', sa.VARCHAR(length=100), nullable=False),
    sa.Column('coursename', sa.VARCHAR(length=100), nullable=False),
    sa.Column('courseid', sa.VARCHAR(length=100), nullable=False),
    sa.Column('moderatorname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('coursecompletiondate', sa.VARCHAR(length=100), nullable=False),
    sa.Column('moderationdate', sa.VARCHAR(length=100), nullable=False),
    sa.Column('question1', sa.VARCHAR(length=10), nullable=False),
    sa.Column('question2', sa.VARCHAR(length=10), nullable=False),
    sa.Column('question3', sa.VARCHAR(length=10), nullable=False),
    sa.Column('question4', sa.VARCHAR(length=10), nullable=False),
    sa.Column('question5', sa.VARCHAR(length=10), nullable=False),
    sa.Column('question6', sa.VARCHAR(length=10), nullable=False),
    sa.Column('question7', sa.VARCHAR(length=10), nullable=False),
    sa.Column('feedback', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=200), nullable=True),
    sa.Column('admin_note', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('studentattemptid')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cell_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('selfie', sa.VARCHAR(length=200), nullable=True),
    sa.Column('id_upload', sa.VARCHAR(length=200), nullable=True),
    sa.Column('role', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('_alembic_tmp_airside_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('airside_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_s', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pdf_filename', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_assessment_quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('option_a', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option_b', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option_c', sa.VARCHAR(length=255), nullable=False),
    sa.Column('option_d', sa.VARCHAR(length=255), nullable=False),
    sa.Column('correct_option', sa.VARCHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_enrollment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('reset_count', sa.INTEGER(), nullable=True),
    sa.Column('approved', sa.BOOLEAN(), nullable=True),
    sa.Column('completed', sa.BOOLEAN(), server_default=sa.text('(FALSE)'), nullable=True),
    sa.Column('certificate_issued', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('certificate_sent_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('certificate_issued_date', sa.DATETIME(), nullable=True),
    sa.Column('enrolled_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('module_id', sa.INTEGER(), nullable=False),
    sa.Column('question', sa.TEXT(), nullable=False),
    sa.Column('correct_answer', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_chapter',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('position', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('chapter_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('quiz_data', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['course_chapter.id'], name='fk_coursechapter_parent'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rpas_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_s', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('chapter_id', sa.INTEGER(), nullable=True),
    sa.Column('is_complete', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('final_assessment_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('student_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('course_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('attempt_no', sa.INTEGER(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('total_questions', sa.INTEGER(), nullable=False),
    sa.Column('correct_count', sa.INTEGER(), nullable=False),
    sa.Column('percentage', sa.INTEGER(), nullable=False),
    sa.Column('passed', sa.BOOLEAN(), nullable=False),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_assessment_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_final_assessment_attempts_student_number', ['student_number'], unique=False)
        batch_op.create_index('ix_final_assessment_attempts_course_key', ['course_key'], unique=False)

    # ### end Alembic commands ###
