"""Add certificate_number and issue_date

Revision ID: c2a503e270d3
Revises: b7e09d5b70ec
Create Date: 2025-04-01 17:49:06.436132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a503e270d3'
down_revision = 'b7e09d5b70ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('certificate_issued_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.drop_column('certificate_issued_date')

    # ### end Alembic commands ###
