"""Add enrolled_at to course_enrollment

Revision ID: c7ea090a610a
Revises: 3728a46da2b3
Create Date: 2025-07-21 12:07:26.143219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7ea090a610a'
down_revision = '3728a46da2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrolled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.drop_column('enrolled_at')

    op.drop_table('violation_log')
    # ### end Alembic commands ###
