"""Create final_assessment_attempts table

Revision ID: c99752274a6b
Revises: 22176b8e927d
Create Date: 2025-10-02 11:51:33.450063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c99752274a6b'
down_revision = '22176b8e927d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rpas_attempt')
    with op.batch_alter_table('proctor_violations', schema=None) as batch_op:
        batch_op.drop_index('ix_proctor_violations_course_key')
        batch_op.drop_index('ix_proctor_violations_created_at')
        batch_op.drop_index('ix_proctor_violations_student_number')

    op.drop_table('proctor_violations')
    op.drop_table('airside_attempt')
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_attempt_course_key')

    op.drop_table('assessment_attempt')
    with op.batch_alter_table('final_assessment_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_final_assessment_attempts_course_key')
        batch_op.drop_index('ix_final_assessment_attempts_student_number')

    op.drop_table('final_assessment_attempts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_assessment_attempts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('student_number', sa.VARCHAR(length=64), nullable=False),
    sa.Column('course_key', sa.VARCHAR(length=64), nullable=False),
    sa.Column('course_id', sa.INTEGER(), nullable=True),
    sa.Column('attempt_no', sa.INTEGER(), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('total_questions', sa.INTEGER(), nullable=False),
    sa.Column('correct_count', sa.INTEGER(), nullable=False),
    sa.Column('percentage', sa.INTEGER(), nullable=False),
    sa.Column('passed', sa.BOOLEAN(), nullable=False),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('review_status', sa.VARCHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('final_assessment_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_final_assessment_attempts_student_number', ['student_number'], unique=False)
        batch_op.create_index('ix_final_assessment_attempts_course_key', ['course_key'], unique=False)

    op.create_table('assessment_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('course_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_s', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_attempt_course_key', ['course_key'], unique=False)

    op.create_table('airside_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_s', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctor_violations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=64), nullable=True),
    sa.Column('course_key', sa.VARCHAR(length=64), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=255), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('extra_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proctor_violations', schema=None) as batch_op:
        batch_op.create_index('ix_proctor_violations_student_number', ['student_number'], unique=False)
        batch_op.create_index('ix_proctor_violations_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_proctor_violations_course_key', ['course_key'], unique=False)

    op.create_table('rpas_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
    sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=True),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('passed', sa.BOOLEAN(), nullable=True),
    sa.Column('answers_json', sa.TEXT(), nullable=True),
    sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_s', sa.INTEGER(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
    sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
