"""Add POPIA consent fields on Student

Revision ID: ca56660d9121
Revises: 79052f0914f3
Create Date: 2025-09-29 09:19:38.572211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca56660d9121'
down_revision = '79052f0914f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('popi_version', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('popi_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('popi_ip', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('popi_user_agent', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_student_popi_accepted_at'), ['popi_accepted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_popi_version'), ['popi_version'], unique=False)

    with op.batch_alter_table('student_deletion_log', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index('idx_sdl_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_sdl_student_id', ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_deletion_log', schema=None) as batch_op:
        batch_op.drop_index('idx_sdl_student_id')
        batch_op.drop_index('idx_sdl_created_at')
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_popi_version'))
        batch_op.drop_index(batch_op.f('ix_student_popi_accepted_at'))
        batch_op.drop_column('popi_user_agent')
        batch_op.drop_column('popi_ip')
        batch_op.drop_column('popi_accepted_at')
        batch_op.drop_column('popi_version')

    # ### end Alembic commands ###
