"""Added approved column to CourseEnrollment

Revision ID: cb7fea5e2d5e
Revises: d3c46fb98ddc
Create Date: 2025-02-17 19:11:24.397034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7fea5e2d5e'
down_revision = 'd3c46fb98ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
