"""Add attempts_used to CourseEnrollment

Revision ID: df527e262e9e
Revises: 2e86a52fce15
Create Date: 2025-12-08 10:47:44.669522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df527e262e9e'
down_revision = '2e86a52fce15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###

    # This table was temporary, safe to drop
    op.drop_table('_alembic_tmp_assessment_attempt')

    # assessment_attempt: just fix id autoincrement / not null
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True
        )

    # 🔧 IMPORTANT: add attempts_used with server_default='0' so old rows don't violate NOT NULL
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'attempts_used',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True
        )
    # If you *really* want to remove the server default later,
    # you can do a follow-up migration. This is fine for now.

    # handbooks: keep type/nullability tweaks, don't play games with unnamed FKs
    with op.batch_alter_table('handbooks', schema=None) as batch_op:
        batch_op.alter_column(
            'course_id',
            existing_type=sa.INTEGER(),
            nullable=True
        )
        batch_op.alter_column(
            'is_active',
            existing_type=sa.BOOLEAN(),
            nullable=False
        )
        # removed: batch_op.drop_constraint(None, type_='foreignkey')

    # popia_consent: type / index / unique fixes, leave FK wiring alone
    with op.batch_alter_table('popia_consent', schema=None) as batch_op:
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True
        )
        batch_op.alter_column(
            'version',
            existing_type=sa.TEXT(),
            type_=sa.String(length=32),
            existing_nullable=False
        )
        batch_op.alter_column(
            'ip_address',
            existing_type=sa.VARCHAR(length=45),
            type_=sa.String(length=64),
            existing_nullable=True
        )
        batch_op.drop_index('uq_popia_consent_student_version')
        batch_op.create_index(
            batch_op.f('ix_popia_consent_student_id'),
            ['student_id'],
            unique=False
        )
        batch_op.create_index(
            batch_op.f('ix_popia_consent_version'),
            ['version'],
            unique=False
        )
        batch_op.create_unique_constraint(
            'uq_popia_student_version',
            ['student_id', 'version']
        )
        # removed:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])

    # support_message: index changes only
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.drop_index('ix_support_message_ticket_created')
        batch_op.drop_index('ix_support_message_ticket_id')
        batch_op.create_index(
            batch_op.f('ix_support_message_created_at'),
            ['created_at'],
            unique=False
        )

    # support_ticket: id/status/created_at + index/unique; leave FKs alone
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            nullable=False
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DATETIME(),
            nullable=False
        )
        batch_op.drop_index('ix_support_ticket_student_created')
        batch_op.create_index(
            'ix_support_ticket_status_created',
            ['status', 'created_at'],
            unique=False
        )
        batch_op.create_unique_constraint(
            'uq_support_ticket_ticket_id',
            ['ticket_id']
        )
        # removed:
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.drop_constraint(None, type_='foreignkey')
        # batch_op.create_foreign_key(None, 'student', ['student_id'], ['id'])
        # batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])

    # violation_log: widen student_id
    with op.batch_alter_table('violation_log', schema=None) as batch_op:
        batch_op.alter_column(
            'student_id',
            existing_type=sa.VARCHAR(length=8),
            type_=sa.String(length=64),
            existing_nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted to match upgrade ###

    # violation_log: revert column type
    with op.batch_alter_table('violation_log', schema=None) as batch_op:
        batch_op.alter_column(
            'student_id',
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=8),
            existing_nullable=True
        )

    # support_ticket: revert id/status/created_at + index/unique
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        # don't touch FKs, we didn't in upgrade
        batch_op.drop_constraint(
            'uq_support_ticket_ticket_id',
            type_='unique'
        )
        batch_op.drop_index('ix_support_ticket_status_created')
        batch_op.create_index(
            'ix_support_ticket_student_created',
            ['student_id', 'created_at'],
            unique=False
        )
        batch_op.alter_column(
            'created_at',
            existing_type=sa.DATETIME(),
            nullable=True
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=20),
            nullable=True
        )
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True
        )

    # support_message: revert index changes
    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_support_message_created_at'))
        batch_op.create_index(
            'ix_support_message_ticket_id',
            ['ticket_id'],
            unique=False
        )
        batch_op.create_index(
            'ix_support_message_ticket_created',
            ['ticket_id', 'created_at'],
            unique=False
        )

    # popia_consent: revert type/index/unique; leave FKs alone
    with op.batch_alter_table('popia_consent', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_popia_student_version',
            type_='unique'
        )
        batch_op.drop_index(batch_op.f('ix_popia_consent_version'))
        batch_op.drop_index(batch_op.f('ix_popia_consent_student_id'))
        batch_op.create_index(
            'uq_popia_consent_student_version',
            ['student_id', 'version'],
            unique=1
        )
        batch_op.alter_column(
            'ip_address',
            existing_type=sa.String(length=64),
            type_=sa.VARCHAR(length=45),
            existing_nullable=True
        )
        batch_op.alter_column(
            'version',
            existing_type=sa.String(length=32),
            type_=sa.TEXT(),
            existing_nullable=False
        )
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True
        )
        # no FK changes here either

    # handbooks: revert nullability tweaks
    with op.batch_alter_table('handbooks', schema=None) as batch_op:
        batch_op.alter_column(
            'is_active',
            existing_type=sa.BOOLEAN(),
            nullable=True
        )
        batch_op.alter_column(
            'course_id',
            existing_type=sa.INTEGER(),
            nullable=False
        )
        # no FK changes

    # course_enrollment: drop attempts_used, revert id
    with op.batch_alter_table('course_enrollment', schema=None) as batch_op:
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True
        )
        batch_op.drop_column('attempts_used')

    # assessment_attempt: revert id
    with op.batch_alter_table('assessment_attempt', schema=None) as batch_op:
        batch_op.alter_column(
            'id',
            existing_type=sa.INTEGER(),
            nullable=True,
            autoincrement=True
        )

    # recreate the temp table if downgrade actually happens
    op.create_table(
        '_alembic_tmp_assessment_attempt',
        sa.Column('id', sa.INTEGER(), nullable=False),
        sa.Column('course_key', sa.VARCHAR(length=64), nullable=True),
        sa.Column('student_id', sa.VARCHAR(length=32), nullable=True),
        sa.Column('student_number', sa.VARCHAR(length=32), nullable=True),
        sa.Column('full_name', sa.VARCHAR(length=128), nullable=True),
        sa.Column('email', sa.VARCHAR(length=128), nullable=True),
        sa.Column('score', sa.FLOAT(), nullable=True),
        sa.Column('passed', sa.BOOLEAN(), nullable=True),
        sa.Column('answers_json', sa.TEXT(), nullable=True),
        sa.Column('video_filename', sa.VARCHAR(length=255), nullable=True),
        sa.Column('started_at', sa.DATETIME(), nullable=True),
        sa.Column('finished_at', sa.DATETIME(), nullable=True),
        sa.Column('duration_s', sa.INTEGER(), nullable=True),
        sa.Column('ip_address', sa.VARCHAR(length=64), nullable=True),
        sa.Column('user_agent', sa.VARCHAR(length=256), nullable=True),
        sa.Column('created_at', sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###