"""Added parent_id to CourseChapter for sub-chapters

Revision ID: f52e785981cf
Revises: 56c6f54fd90e
Create Date: 2025-02-19 15:12:12.010996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f52e785981cf'
down_revision = '56c6f54fd90e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_coursechapter_parent', 'course_chapter', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.drop_constraint('fk_coursechapter_parent', type_='foreignkey')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
