"""Add media_url to CourseChapter

Revision ID: f7f13690eabe
Revises: 4c9a6249e2b3
Create Date: 2025-03-31 12:26:57.839365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f13690eabe'
down_revision = '4c9a6249e2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_chapter', schema=None) as batch_op:
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
